### PR TITLE
Handle missing projects gracefully and fix typo.

### PR DESCRIPTION
**Pull request by micrypt**
Fixed what appears to to have been a typo. Also attempted to add a clear error message when anticipated project is not present in Pinax.

### CODE REVIEW

**Comment by ossanna16** [comment]
@micrypt Thank you! All checks have failed on this. Could you look into this please?

**Comment by micrypt** [comment]
@ossanna16 Curious. The checks seem to have failed for reasons unrelated to this change. It appears there's an issue with the Travis environment. Error message: `The command "tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO" exited with 1.`

**Comment by ossanna16** [comment]
@brosner Could you please look into this?

**Comment by paltman** [comment]
There is something funky going on with Travis it seems.  Our config hasn't changed in a long time and the output indicates that the `TRAVIS_PYTHON_VERSION` and `DJANGO` env variables are evaluating to nothing.

**Comment by paltman** [comment]
Actually, I don't think it has ever worked.

**Comment by paltman** [comment]
Thanks @micrypt!

**Pull request merged**
